star 1.4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,13 +1,15 @@
-echo 'configure is no longer used - just type "make"'
-echo 'Supported make programs are:'
+#!/bin/sh -
+echo 'configure is no longer used - just type "make", supported make programs are:'
 echo ''
 echo 'smake	-	The Schily smake program'
 echo '			This is the preferred make program, the source can be'
 echo '			found on ftp://ftp.fokus.gmd.de/pub/unix/smake/alpha/'
 echo ''
-echo 'make	-	SunPRO make, SunPRO make is located'
+echo '		Smake is the only make program with automake features, it is'
+echo '		the only program that works on unknown platforms.'
+echo ''
+echo 'make	-	SunPRO make (on SunOS/Solaris only)'
 echo '			in /usr/bin/ (SunOS 4.x) or /usr/ccs/bin/ (Solaris)'
-echo '			make programs from other OS will not work'
 echo ''
 echo 'gmake	-	GNU make'
 echo '			GNU make will not work correctly on all platforms'
@@ -15,10 +17,15 @@ echo '			and due to some conceptional bugs output several'
 echo '			error messages that are not related to the makefile'
 echo '			system but to GNU make (see README.gmake)'
 echo ''
-echo 'All other make programs will not work at all, for more information'
-echo 'read README.compile'
+echo 'Other make programs will not work, for more information read README.compile'
 echo ''
 echo 'If you have problems and if you are in doubt, try to use smake'
 echo '	Always compile the latest version that can be found on:'
 echo '		ftp://ftp.fokus.gmd.de/pub/unix/smake/alpha/'
 echo ''
+#
+# Make automated procedures that believe all programs still use the outdated GNU
+# "./configure; make" procedure think configure failed and get the attention of
+# a human ...
+#
+exit 1
