star 1.5

diff --git a/conf/makeinc b/conf/makeinc
--- a/conf/makeinc
+++ b/conf/makeinc
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# @(#)makeinc	1.3 02/12/16 Copyright 1998 J. Schilling
+# @(#)makeinc	1.4 05/05/01 Copyright 1998 J. Schilling
 ###########################################################################
 # Copyright 1998 by J. Schilling
 ###########################################################################
@@ -17,19 +17,15 @@
 #	./RULES/sun4c-sunos-gcc.rul
 #
 ###########################################################################
-# This program is free software; you can redistribute it and/or modify
-# it under the terms of the GNU General Public License as published by
-# the Free Software Foundation; either version 2, or (at your option)
-# any later version.
+# The contents of this file are subject to the terms of the
+# Common Development and Distribution License, Version 1.0 only.
+# (the "License").  You may not use this file except in compliance
+# with the License.
 #
-# This program is distributed in the hope that it will be useful,
-# but WITHOUT ANY WARRANTY; without even the implied warranty of
-# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-# GNU General Public License for more details.
+# See the file CDDL.Schily.txt in this distribution for details.
 #
-# You should have received a copy of the GNU General Public License along with
-# this program; see the file COPYING.  If not, write to the Free Software
-# Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
+# When distributing Covered Code, include this CDDL HEADER in each
+# file and include the License file CDDL.Schily.txt from this distribution.
 ###########################################################################
 MAILADDR=schilling@fokus.fhg.de
 
@@ -46,32 +42,35 @@ case $1 in
 esac
 
 if [ $# -lt 1 ]; then
-	echo 'Usage: makeinc [-r srcroot] filename'
+	echo 'Usage: makeinc [-r srcroot] filename'	1>&2
+	exit 1
 fi
 
 ###########################################################################
 # Find SRCROOT if not specified via option
 ###########################################################################
-if [ .$SRCROOT = . -a -r RULES ]; then
+if [ .$SRCROOT = . ]; then
 	SRCROOT=.
-fi
-if [ .$SRCROOT = . -a -r ../RULES ]; then
-	SRCROOT=..
-fi
-if [ .$SRCROOT = . -a -r ../../RULES ]; then
-	SRCROOT=../..
-fi
-if [ .$SRCROOT = . -a -r ../../../RULES ]; then
-	SRCROOT=../../..
-fi
-if [ .$SRCROOT = . -a -r ../../../../RULES ]; then
-	SRCROOT=../../../..
-fi
-if [ .$SRCROOT = . -a -r ../../../../../RULES ]; then
-	SRCROOT=../../../../..
-fi
-if [ .$SRCROOT = . -a -r ../../../../../../RULES ]; then
-	SRCROOT=../../../../../..
+	loop=1
+	while [ $loop -lt 100 ]; do
+		if [ ! -d $SRCROOT ]; then
+			# Abort on ENAMETOOLONG
+			break
+		fi
+		if [ -r $SRCROOT/RULES/rules.top ]; then
+			break
+		fi
+		if [ "$SRCROOT" = . ]; then
+			SRCROOT=".."
+		else
+			SRCROOT="$SRCROOT/.."
+		fi
+		loop="`expr $loop + 1`"
+	done
+	if [ ! -r $SRCROOT/RULES/rules.top ]; then
+		echo "Cannot find SRCROOT directory" 1>&2
+		exit 1
+	fi
 fi
 
 ###########################################################################
